name: com_cipherschools_assignment
description: "A new Flutter project."

publish_to: 'none' 



environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  flutter_riverpod: ^2.6.1
  google_fonts: ^6.2.1
  hive: ^2.2.3
  build_runner: ^2.4.9
  hive_generator: ^2.0.1
  shared_preferences: ^2.2.3
  cloud_firestore: ^5.4.0
  animated_text_kit: ^4.2.3
  uuid: ^4.5.1
  path_provider: ^2.1.4
  intl: ^0.20.2
  fl_chart: ^0.67.0
  
 

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^3.0.0


flutter:

 
  uses-material-design: true

  assets:
    - assets/images/
 
